# Generated by Django 3.2.6 on 2021-10-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(help_text='File ID', primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=128, verbose_name='파일명')),
                ('threshold', models.PositiveIntegerField(default=80, verbose_name='임계치')),
                ('commit_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('description', models.TextField(verbose_name='설명')),
                ('commit_status', models.CharField(choices=[('WAIT', '분석대기'), ('ONGO', '분석중'), ('DONE', '분석완료')], default='WAIT', max_length=4, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(help_text='Page ID', primary_key=True, serialize=False)),
                ('page_num', models.PositiveIntegerField(verbose_name='페이지')),
                ('is_safe', models.BooleanField(default=False, verbose_name='안전여부')),
                ('box_json', models.CharField(max_length=128)),
                ('file', models.ForeignKey(db_column='file', on_delete=django.db.models.deletion.CASCADE, related_name='file', to='mysite.file')),
            ],
        ),
    ]
