# Generated by Django 3.2.6 on 2021-10-14 02:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uploader.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threshold', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(help_text='File ID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=uploader.utils.rename_file_to_uuid, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif'])])),
                ('filename', models.CharField(max_length=128, verbose_name='파일명')),
                ('commit_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('description', models.TextField(verbose_name='설명')),
                ('result', models.CharField(blank=True, choices=[('DANGER', '위험'), ('SAFE', '안전')], max_length=10, null=True, verbose_name='결과')),
                ('commit_status', models.CharField(blank=True, choices=[('WAIT', '분석대기'), ('ONGO', '분석중'), ('DONE', '분석완료')], default='WAIT', max_length=4, null=True, verbose_name='상태')),
                ('threshold', models.ForeignKey(default=80, on_delete=django.db.models.deletion.SET_DEFAULT, to='threshold.setthreshold', verbose_name='임계치')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(help_text='Page ID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('filename', models.CharField(max_length=128, null=True)),
                ('page_num', models.PositiveIntegerField(verbose_name='페이지')),
                ('img_dir', models.TextField(blank=True, null=True, verbose_name='이미지')),
                ('box_json', models.CharField(max_length=128, null=True)),
                ('content', models.TextField(null=True, verbose_name='내용')),
                ('is_safe', models.BooleanField(default=False, null=True, verbose_name='안전여부')),
                ('file', models.ForeignKey(blank=True, db_column='file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file', to='mysite.file', verbose_name='파일')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
