# Generated by Django 3.2.6 on 2021-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='commit_status',
            field=models.CharField(choices=[('WAIT', '분석대기'), ('ONGO', '분석중'), ('DONE', '분석완료')], default='WAIT', max_length=4, verbose_name='상태'),
        ),
    ]
