# Generated by Django 3.2.6 on 2021-10-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.ForeignKey(db_column='file', on_delete=django.db.models.deletion.CASCADE, related_name='file', to='mysite.file', verbose_name='파일'),
        ),
    ]
