# Generated by Django 3.2.6 on 2021-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='box_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
