# Generated by Django 3.2.6 on 2021-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_page_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='result',
            field=models.CharField(blank=True, choices=[('DANGER', '위험'), ('SAFE', '안전')], max_length=10, null=True, verbose_name='결과'),
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='page',
            name='filename',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='img_dir',
            field=models.TextField(blank=True, null=True, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='file',
            name='commit_status',
            field=models.CharField(blank=True, choices=[('WAIT', '분석대기'), ('ONGO', '분석중'), ('DONE', '분석완료')], default='WAIT', max_length=4, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='page',
            name='box_json',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_safe',
            field=models.BooleanField(default=False, null=True, verbose_name='안전여부'),
        ),
    ]
