# Generated by Django 3.2.6 on 2021-09-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=40, null=True)),
                ('file', models.FileField(blank=True, upload_to='upload/')),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Type1', 'type1'), ('Type2', 'type2'), ('Type3', 'type3')], max_length=50)),
            ],
        ),
    ]
