# Generated by Django 3.2.6 on 2021-10-05 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20211002_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif'])]),
        ),
    ]
