# Generated by Django 3.2.6 on 2021-10-07 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif'])]),
        ),
    ]
