# Generated by Django 3.2.6 on 2021-10-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_auto_20211011_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_list',
            field=models.TextField(null=True),
        ),
    ]
