# Generated by Django 3.2.6 on 2021-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_uploadfile_file_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='img',
        ),
        migrations.AddField(
            model_name='page',
            name='filename',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='img_dir',
            field=models.TextField(blank=True, null=True, verbose_name='이미지'),
        ),
    ]
