# Generated by Django 3.2.6 on 2021-10-11 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uploader.utils


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20211011_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_list',
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.ForeignKey(db_column='file', on_delete=django.db.models.deletion.CASCADE, related_name='file_origin', to='uploader.uploadfile', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=uploader.utils.rename_file_to_uuid, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif', 'jpeg'])]),
        ),
    ]
