# Generated by Django 3.2.6 on 2021-10-11 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uploader.utils


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_auto_20211011_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='file',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_tif',
            field=models.ForeignKey(db_column='tif_file', on_delete=django.db.models.deletion.CASCADE, related_name='file_tif', to='uploader.uploadfile', verbose_name='파일원본'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=uploader.utils.rename_file_to_uuid, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif', 'jpeg'])]),
        ),
    ]
