# Generated by Django 3.2.6 on 2021-10-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_auto_20211011_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_tif',
        ),
        migrations.RemoveField(
            model_name='file',
            name='threshold',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
