# Generated by Django 3.2.6 on 2021-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionadd',
            name='ent_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sanctionalt',
            name='ent_num',
            field=models.PositiveIntegerField(),
        ),
    ]
