# Generated by Django 3.2.6 on 2021-10-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0002_auto_20211003_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctionadd',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sanctionalt',
            name='id',
        ),
        migrations.AlterField(
            model_name='sanctionadd',
            name='add_num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanctionalt',
            name='alt_num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
