# Generated by Django 3.2.6 on 2021-09-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-registered_date',)},
        ),
    ]
