# Generated by Django 3.2.6 on 2021-10-14 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(verbose_name='임계치')),
                ('set_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록시간')),
            ],
        ),
    ]
