# Generated by Django 3.2.6 on 2021-10-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setthreshold',
            name='threshold',
            field=models.PositiveIntegerField(verbose_name='임계치'),
        ),
    ]
